[tool.cibuildwheel]

build-frontend = "build"

skip = [
  "*i686",
  "*musl*",
  "*ppc64le",
  "*s390x",
  "*win32",
  "pp*",
]

macos.archs = ["x86_64", "arm64"]

build-verbosity = 1

linux.before-build = [
  "yum makecache fast",
  "yum install -y boost-devel gsl-devel >/dev/null",
  "make swig",
]

macos.before-build = [
  "brew install boost gsl",
  "make swig",
]


test-skip = [
  "*aarch64*",
  "*arm64*",
  "*ppc64*",
  "*s390x*",
]


linux.before-test = [
  "yum install -y parallel >/dev/null",
  "pip install biopython matplotlib numpy pandas pygments scipy"
]

linux.test-command = [
  "cd {project} && bash ./run-examples --skip-slow"
]


macos.before-test = [
  "brew install parallel >/dev/null",
  "pip install biopython matplotlib numpy pandas pygments scipy"
]

# Tests are very slow on mac, so only do basics
macos.test-command = [
  "cd {project} && python examples/example.py"
]
