[tool.cibuildwheel]

build-frontend = "build"

skip = [
  "*i686",
  "*musl*",
  "*ppc64le",
  "*s390x",
  "*win32",
  "pp*",
]

macos.archs = ["x86_64", "arm64"]

build-verbosity = 1

linux.before-build = [
  "yum makecache fast",
  "yum install -y boost-devel gsl-devel >/dev/null",
  "make swig",
]

macos.before-build = [
  "brew install boost gsl",
  "make swig",
]


test-skip = [
  "*aarch64*",
  "*arm64*",
  "*ppc64*",
  "*s390x*",
]

linux.before-test = [
  "yum install -y parallel time >/dev/null",
  "pip install biopython matplotlib numpy pandas pygments scipy"
]

macos.before-test = [
  "export PATH=\"$(brew --prefix)/opt/gnu-time/libexec/gnubin:$PATH\"",
  "brew install gnu-time parallel >/dev/null",
  "pip install biopython matplotlib numpy pandas pygments scipy"
]

test-command = [
  "cd {project} && ./run-examples --skip-slow"
]

